### ISSUE TITLE
Lottie animation not shown in iOS - works in Android

### ISSUE THREAD

**Issue by andremartin** [timbru31/cordova-plugin-lottie-splashscreen#322]
# Bug report

Run the demo with instructions listed under: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/tree/master/example

## Expected output

Lottie animation that disappears after 10s.

## What do you see instead?

White screen that disappears after a while (once the animation is over time wise I assume).

## Version information

macOS 12.2.3
Xcode 12.4
Cordova 9.0.1
npm 6.14.8

## Please provide any additional information below.

Animation is also not shown if show is invoked manually as shown below:

![Screencast](https://user-images.githubusercontent.com/2954143/121808266-e8823300-cc57-11eb-8aba-c343d8bab683.gif)

**Comment by timbru31** [comment]
Thanks for the report. Can you give me the iOS version you are testing with?

**Comment by andremartin** [comment]
iOS 14.4

**Comment by timbru31** [comment]
Thanks, indeed the default config used a private IP for the iOS animation location. Documentation has been corrected!

**Comment by andremartin** [comment]
I think there is still an issue since the Javascript call as shown in the screencast above with this valid and public URL: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/raw/master/example/www/lottie/data.json should have displayed a lottie animation, or shouldn't it?

**Comment by andremartin** [comment]
This is what I did, if you zoom into the screencast, or didn't I?

**Comment by timbru31** [comment]
Oh yes, missed it. Will try it on my end, too.

**Comment by timbru31** [comment]
Works fine in my Simulator (iOS 12.4)
