### ISSUE TITLE
ionic 6 and capacitor 4 issue

### ISSUE THREAD

**Issue by chidav77** [timbru31/cordova-plugin-lottie-splashscreen#486]
![Simulator Screen Shot - iPhone 14 Pro - 2022-09-16 at 15 55 04](https://user-images.githubusercontent.com/642584/190643663-38947c1d-9dc5-4701-800c-b59cb8dd8c90.png)
After installing the plugin in a clean new project, on ios it shows up the lottie animation but is way off-center, smaller and it also displays a rectangular background in the middle on the screen ( please check ios screenshot ).
On Android, it is not building at all. I get this error in android studio logcat:

```
2022-09-16 15:42:08.749 15824-15824/nl.xxxxx.lab E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.xxxxx.lab, PID: 15824
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.apache.cordova.CordovaWebViewEngine.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
        at de.dustplanet.cordova.lottie.LottieSplashScreen$addAnimationListeners$1.onAnimationStart(LottieSplashScreen.kt:284)
        at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:584)
        at com.airbnb.lottie.utils.BaseLottieAnimator.notifyStart(BaseLottieAnimator.java:57)
        at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:207)
        at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:445)
        at com.airbnb.lottie.LottieDrawable$2.run(LottieDrawable.java:438)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:229)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:550)
        at de.dustplanet.cordova.lottie.LottieSplashScreen.createLottieComposition$lambda-3(LottieSplashScreen.kt:200)
        at de.dustplanet.cordova.lottie.LottieSplashScreen.$r8$lambda$Z5JPNbsIT5QwjkWf2fsGcnuDdsk(Unknown Source:0)
        at de.dustplanet.cordova.lottie.LottieSplashScreen$$ExternalSyntheticLambda1.onResult(Unknown Source:4)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:144)
        at com.airbnb.lottie.LottieTask.access$100(LottieTask.java:27)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:131)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

My env:
```
Ionic:

   Ionic CLI                     : 6.20.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.7
   @angular-devkit/build-angular : 14.2.3
   @angular-devkit/schematics    : 14.2.3
   @angular/cli                  : 14.2.3
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.2.0
   @capacitor/android : 4.2.0
   @capacitor/core    : 4.2.0
   @capacitor/ios     : 4.2.0

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.0

System:

   NodeJS : v14.20.0 (/opt/homebrew/Cellar/node@14/14.20.0/bin/node)
   npm    : 6.14.17
   OS     : macOS Monterey
```

_Originally posted by @xyboox in https://github.com/timbru31/cordova-plugin-lottie-splashscreen/discussions/475_

**Comment by rahul-bmninfotech** [comment]
until he is not solving the issue, you can create the custom Splash component and use in `app.component.ts` like:

![image](https://user-images.githubusercontent.com/110603639/202705043-e0fa0232-3671-42af-9685-85c4125b1cb3.png)

 use: @lottiefiles/lottie-player to play the animation in component

after create the capacitor build: `(ionic cap build android)`

remove this attribute from `AndroidManifest.xml`

![image](https://user-images.githubusercontent.com/110603639/202705555-2bfa4b7f-2a2a-44ae-b73c-3268f67ae814.png)

Hope this will help

**Comment by chidav77** [comment]
> until he is not solving the issue, you can create the custom Splash component and use in `app.component.ts` like:
> 
> ![image](https://user-images.githubusercontent.com/110603639/202705043-e0fa0232-3671-42af-9685-85c4125b1cb3.png)
> 
> use: @lottiefiles/lottie-player to play the animation in component
> 
> ![image](https://user-images.githubusercontent.com/110603639/202705786-f910f98c-b50c-487e-b97c-b8a4fb3c201f.png)
> 
> after create the capacitor build: `(ionic cap build android)`
> 
> remove this attribute from `AndroidManifest.xml`
> 
> ![image](https://user-images.githubusercontent.com/110603639/202705555-2bfa4b7f-2a2a-44ae-b73c-3268f67ae814.png)
> 
> Hope this will help

Oh thanks. This is a nice workaround.
Just a question if you can clarify a bit..
Why is needed the deletion of the android theme attribute in manifest?
Does it affects how the app works?

Thanks!

**Comment by rahul-bmninfotech** [comment]
it's loading the `styles.xml` and in this file, it's loading the default static splash screens, if you will not remove this, it will keep loading the static splash screens on the app loading.

![image](https://user-images.githubusercontent.com/110603639/202970359-904d7f6a-8507-42d0-aff5-33855c453d0f.png)

by removing this attribute we are just preventing android to load the default splash screen and default android splash screen.

On another hand, when we are showing a splash screen from the app component, that means the platform has been already loaded, you can simply hide by giving the duration to the modal component.

**Comment by kurtiev** [comment]
@chidav77 Didn't solve it? Faced the same issue.

**Comment by chidav77** [comment]
> @chidav77 Didn't solve it? Faced the same issue.

No. Seems no one fixed this issue

**Comment by kurtiev** [comment]
ok, let me know please if you'll find a way how to fix that, especially on iOS. Thanks.  @chidav77

**Comment by danielzen** [comment]
Same issue, Capacitor 4.6.1, Angular 15.

**Comment by LAccastello** [comment]
Same problem here. I wasn't be able to fix it.

**Comment by martinglover** [comment]
I was getting this same issue, run `npm i https://github.com/timbru31/cordova-plugin-lottie-splashscreen` 
Seems there are issues have been fixed but had no release created

**Comment by timbru31** [comment]
Released v0.10.0 with a fix for the crash. Proper Capacitor support will be handled separately.

**Comment by kurtiev** [comment]
Still getting issues
<img width="114" alt="image" src="https://user-images.githubusercontent.com/15800725/220905477-e1eeb545-301e-4029-8568-0d9dc6dc761f.png">

**Comment by elmartino** [comment]
same issue here
